kind: pipeline
name: Frontend latest lint

steps:
- name: lint
  image: node:latest
  commands:
  - cd Frontend
  - npm install
  - npm run lint

---

kind: pipeline
name: Frontend version lint

steps:
- name: lint
  image: node:11
  commands:
  - cd Frontend
  - npm install
  - npm run lint

---

kind: pipeline
name: Frontend latest build

steps:
- name: build
  image: node:latest
  commands:
  - cd Frontend
  - npm install
  - npm run build

---

kind: pipeline
name: Frontend version build

steps:
- name: build
  image: node:11
  commands:
  - cd Frontend
  - npm install
  - npm run build

---

kind: pipeline
name: GoBackend latest test
workspace:
    base: /go
    path: src/github.com/LucienShui/PasteMe

services:
- name: mysql
  image: mysql:latest
  ports:
  - 3306
  environment:
    MYSQL_USER: username
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: pasteme

steps:
- name: test
  image: golang:latest
  commands:
  - sleep 15
  - cd GoBackend
  - go test ./tests

---

kind: pipeline
name: gobackend_latest build
workspace:
    base: /go
    path: src/github.com/LucienShui/PasteMe

steps:
- name: build
  image: golang:latest
  commands:
  - cd GoBackend
  - go build -o pasteme_server
