language: bash

script:
  - rm -rf .git
  - git clone https://${GH_REF} -b ${P_BRANCH} tmpdir
  - cp DOCKER_DEPLOY.md tmpdir/README.md
  - cp docker-compose.yml tmpdir/
  - cd tmpdir/
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add --all
  - git commit -m "build from travis-ci `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
  - git push https://${GH_TOKEN}@${GH_REF} ${P_BRANCH}

branches:
  only:
    - master

notifications:
  email:
    - lucien@lucien.ink
  on_failure: always

env:
  global:
    - GH_REF: github.com/LucienShui/PasteMe.git
    - P_BRANCH: docker

addons:
  hosts:
    - ${WEBHOOK}