language: node_js

node_js:
  - "11"

before_install:
  - cd Frontend

install:
  - npm install

script:
  - npm run build

after_success:
  - rm -rf .git
  - git clone https://${GH_REF} -b ${P_BRANCH} tmpdir
  - rm -rf tmpdir/*
  - cp -r pasteme/* tmpdir
  - cp config.example.json tmpdir
  - cd tmpdir
  - rm config.json
  - cp -r ../../Backend api
  - cp ../../LICENSE ../../DEPLOY.md ../../.gitignore ./
  - mv DEPLOY.md README.md
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add --all
  - git commit -m "build from travis-ci `TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S'`"
  - git push https://${GH_TOKEN}@${GH_REF} ${P_BRANCH}
  

branches:
  only:
    - master

notifications:
  email:
    - lucien@lucien.ink
  on_failure: always

env:
  global:
    - GH_REF: github.com/LucienShui/PasteMe.git
    - P_BRANCH: build
